name: easy_crm
description: "Cadastro e controle de clientes"
publish_to: 'none'
version: 0.2.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  brasil_fields: ^1.14.1
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  flutter_riverpod: ^2.5.1
  http: ^1.2.1
  intl: ^0.18.1
  path: ^1.9.0
  riverpod_annotation: ^2.3.5
  share_plus: ^9.0.0
  sqflite: ^2.3.2
  url_launcher: ^6.2.5
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.8
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
